build:
	# gcc string_alphabate.c
	# gcc search_totall_word.c filter.c -fsanitize=address -g
	# gcc search_word.c filter.c
	#gcc Project1.c -lm -fsanitize=address
	#gcc AirPlane.c

	gcc sum.h
	gcc sum.c
	
run:
	./a.out